Repository Jeongyounghyeon/webserv, pull requests merged in 2024-04, with the labels that each got.

#21 [#9] Request Message 파싱 알고리즘 구현
  src/abnf.cpp
  src/abnf.hpp
  src/request.cpp
  src/request.hpp
  src/url.cpp
  src/url.hpp
  src/utils.cpp
  src/utils.hpp
Labels: enhancement

#25 [#22] Reconstruct URI 메서드 구현
  src/abnf.cpp
  src/abnf.hpp
  src/request.cpp
  src/request.hpp
  src/uri.cpp
  src/uri.hpp
Labels: enhancement

#26 서버 구현
  Makefile
  conf/default.conf
  src/client.cpp
  src/client.hpp
  src/main.cpp
  src/multiplexer.cpp
  src/multiplexer.hpp
  src/multiplexing.cpp
  src/multiplexing.hpp
  src/socket.cpp
  src/socket.hpp
  src/utils.cpp
  src/utils.hpp
Labels: enhancement

#28 [#10] 정적파일에 대한 GET 메서드 응답 구현
  src/get.cpp
  src/get.hpp
  src/request.cpp
  src/request.hpp
  src/response.cpp
  src/response.hpp
  src/uri.cpp
  src/uri.hpp
  src/utils.cpp
  src/utils.hpp
  www/.DS_Store
  www/cgi-bin/welcome.py
  www/static/css/style.css
  www/static/form.html
  www/static/index.html
  www/test.cpp
Labels: enhancement

#30 [#29] TCP 코드와 HTTP 코드 병합, index.html에 대한 요청 처리 확인
  Makefile
  conf/default.conf
  src/multiplexer.cpp
  src/multiplexer.hpp
  src/request.cpp
  src/request.hpp
  src/response.cpp
  src/response.hpp
  src/uri.cpp
  www/static/css/style.css
Labels: enhancement

#32 [#27] multiplexing server 구체화
  Makefile
  conf/default.conf
  src/client.cpp
  src/client.hpp
  src/configuration.cpp
  src/configuration.hpp
  src/configuration_parser.cpp
  src/configuration_parser.hpp
  src/main.cpp
  src/multiplexer.cpp
  src/multiplexer.hpp
  src/multiplexing.cpp
  src/multiplexing.hpp
  src/response.cpp
  src/server.cpp
  src/server.hpp
  src/socket.cpp
  src/socket.hpp
Labels: enhancement

#35 [#34] Configuration 보완
  src/configuration.cpp
  src/configuration.hpp
  src/configuration_parser.cpp
  src/configuration_parser.hpp
  src/file_reader.cpp
  src/file_reader.hpp
  src/main.cpp
  src/response.cpp
  src/response.hpp
  src/server.cpp
Labels: enhancement

#37 [#31] CGI 처리 메서드 구현
  src/cgi.cpp
  src/cgi.hpp
  src/get.cpp
  src/get.hpp
  src/multiplexer.cpp
  src/response.cpp
  src/response.hpp
  src/uri.cpp
  src/uri.hpp
  src/utils.cpp
  src/utils.hpp
  www/.DS_Store
  www/cgi-bin/cgi_tester.cgi
  www/cgi-bin/upload.py
  www/cgi-bin/welcome.py
  www/static/.DS_Store
  www/static/form.html
  www/static/upload.html
  www/test.cpp
Labels: enhancement

#39 [#36] Server 보완 (재구현) [not closes]
  Makefile
  src/client.cpp
  src/client.hpp
  src/multiplexer.cpp
  src/multiplexer.hpp
  src/request.cpp
  src/request.hpp
  src/response.cpp
  src/response.hpp
  src/server.cpp
  src/server.hpp
Labels: enhancement

#41 [#34] Configuration 보완 (configuration 중복 directive 에러 처리 추가)
  src/configuration_parser.cpp
Labels: enhancement

#42 [#40] HTTP 요청 응답 처리 기능 리팩토링
  src/abnf.cpp
  src/abnf.hpp
  src/cgi.cpp
  src/cgi.hpp
  src/entity.cpp
  src/entity.hpp
  src/http.cpp
  src/http.hpp
  src/main.cpp
  src/multiplexer.cpp
  src/request.cpp
  src/request.hpp
  src/response.cpp
  src/response.hpp
  src/transaction.cpp
  src/transaction.hpp
  src/uri.cpp
  src/uri.hpp
Labels: enhancement

#43 [#40] HTTP 메서드 구현
  src/cgi.cpp
  src/cgi.hpp
  src/entity.cpp
  src/entity.hpp
  src/http.cpp
  src/http.hpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#44 [#40] HTTP 응답 메시지 생성 메서드(CreateResponseMessage) 구현
  src/entity.cpp
  src/entity.hpp
  src/http.hpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#45 [#36] 서버 보완, 코드 병합 완료
  Makefile
  src/cgi.cpp
  src/cgi.hpp
  src/client.cpp
  src/client.hpp
  src/entity.cpp
  src/entity.hpp
  src/event_handler.cpp
  src/event_handler.hpp
  src/main.cpp
  src/multiplexer.cpp
  src/multiplexer.hpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#50 [#46] 설정파일 처리 메서드 수정
  src/entity.cpp
  src/transaction.cpp
  src/transaction.hpp
  src/uri.cpp
  src/uri.hpp
Labels: bug, enhancement

#48 [#47] error_page directive의 역할 변경
  conf/default.conf
  src/configuration.cpp
  src/configuration.hpp
  src/configuration_parser.cpp
  src/configuration_parser.hpp
Labels: enhancement

#52 [#46] 설정파일 처리 메서드 수정
  src/entity.cpp
  src/transaction.cpp
  src/transaction.hpp
  src/uri.cpp
  src/uri.hpp
Labels: bug, enhancement

#54 [#46] 설정파일 처리 메서드 수정
  src/entity.cpp
  src/transaction.cpp
  src/transaction.hpp
  src/uri.cpp
  src/uri.hpp
Labels: bug, enhancement

#55 feat: error_page directive의 역할 변경
  conf/default.conf
  src/configuration.cpp
  src/configuration.hpp
  src/configuration_parser.cpp
  src/configuration_parser.hpp
Labels: enhancement

#56 [#47] configuration file 에서 client_max_body_size domain 변경
  conf/default.conf
  src/configuration.cpp
  src/configuration.hpp
  src/configuration_parser.cpp
  src/configuration_parser.hpp
  src/utils.cpp
  src/utils.hpp
  webserv
Labels: enhancement

#58 [#57] server 부분 요구사항 만족을 위한 작업
  src/multiplexer.cpp
Labels: enhancement

#64 feat: Request Parsing 조건 변경
  src/multiplexer.cpp
  src/multiplexer.hpp
  webserv
Labels: enhancement

#61 [#60] feat: server error 발생시 status 변경 코드 구현
  src/multiplexer.cpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#65 [#63] 없는 기능에 대한 남겨놓은 todo 작업
  src/multiplexer.cpp
  src/multiplexer.hpp
Labels: enhancement

#68 [#67] URI Percent-Encoding 디코더 기능 구현
  conf/default.conf
  src/transaction.cpp
  src/uri.cpp
  src/uri.hpp
  www/static/a
  www/static/error_page.html
Labels: enhancement

#70 [#69] client에게 Response send 후 client 정보 초기화
  src/client.cpp
  src/client.hpp
  src/multiplexer.cpp
Labels: enhancement

#72 [#71] keep-alive 구현
  src/multiplexer.cpp
Labels: enhancement

#73 [#23] Request-Body 파싱 로직 구현
  src/multiplexer.cpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#78 [#77] HTTP Connection 헤더 로직 구현
  src/abnf.cpp
  src/abnf.hpp
  src/http.cpp
  src/http.hpp
  src/transaction.cpp
  src/utils.cpp
  src/utils.hpp
Labels: enhancement

#80 [#79] HTTP 기능 클래스의 대입 연산자 및 접근자 수정
  src/cgi.cpp
  src/cgi.hpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#82 [#81] CGI 대입 연산자 수정
  src/cgi.cpp
  src/cgi.hpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#85 [#84] Server Refactoring
  Makefile
  src/client.cpp
  src/client.hpp
  src/event_handler.cpp
  src/event_handler.hpp
  src/main.cpp
  src/multiplexer.cpp
  src/multiplexer.hpp
  src/server.cpp
  src/server.hpp
  src/socket.cpp
  src/socket.hpp
Labels: enhancement

#87 [#86] keep-alive 적용
  src/event_handler.cpp
  src/event_handler.hpp
  src/multiplexer.cpp
Labels: enhancement

#90 [#89] Event handler Delete method 수정
  src/event_handler.cpp
Labels: bug

#91 [#74]: CGI 환경변수 추가
  a.out
  src/abnf.cpp
  src/abnf.hpp
  src/cgi.cpp
  src/client.cpp
  src/http.cpp
  src/http.hpp
  src/transaction.cpp
  test.cpp
  uploads/username
  webserv
  www/cgi-bin/upload.php
  www/cgi-bin/upload.py
  www/cgi-bin/welcome.py
Labels: bug

#94 [#93] 같은 요청에 한번의 request parsing
  src/client.cpp
  src/client.hpp
  src/multiplexer.cpp
Labels: enhancement

#96 [#74] File upload 기능 구현
  src/cgi.cpp
  src/client.cpp
  src/http.cpp
  src/transaction.cpp
  test.cpp
  www/cgi-bin/upload.py
  www/static/upload.html
Labels: enhancement

#97 [#95] cgi에 문제가 있던 부분 처리
  src/cgi.cpp
  src/multiplexer.cpp
Labels: bug

#100 [#98] DELETE, Status 414, CGI 수정
  conf/default.conf
  src/cgi.cpp
  src/transaction.cpp
  src/uri.cpp
  www/cgi-bin/upload.py
  www/upload/main.cpp
Labels: enhancement

#101 [#99] 평가 전 테스트, 보완
  src/cgi.cpp
  src/cgi.hpp
  src/multiplexer.cpp
  src/transaction.cpp
  src/transaction.hpp
Labels: enhancement

#111 [#110] file descriptor를 읽고 쓸때 event를 받아야 하는 조건 적용
  src/cgi.cpp
  src/cgi.hpp
  src/multiplexer.cpp
Labels: enhancement

#113 [#112] Log 및 정리
  src/configuration_parser.cpp
  src/file_reader.cpp
  src/main.cpp
  src/multiplexer.cpp
  src/socket.cpp
  www/upload/Fixed.cpp
Labels: enhancement
